### ISSUE TITLE
Additional chart maintainers

### ISSUE THREAD

**Issue by scottrigby** [prometheus-community/helm-charts#21]
## Problem

Good summary from @torstenwalter https://github.com/prometheus-community/helm-charts/issues/21#issuecomment-687666865:

> When introducing [CODEOWNERS](https://github.com/prometheus-community/helm-charts/blob/main/.github/CODEOWNERS) we will have an issue with charts which only have one maintainers. If that maintainer make a change then he is not able to approve it. Repository admins would need to use their "superpower" to override the required review and can merge it. That might be ok for the start, but I would suggest that we try to add at least a second maintainer there.

## Solution

Also from https://github.com/prometheus-community/helm-charts/issues/21#issuecomment-687666865:
> Would be great if we could find volunteers here or even better if the chart maintainers could try to motivate people who already contributed to the chart to become maintainer.

We have arrived at a process:

1. Open a PR proposing yourself as a co-maintainer of one of the charts in need
1. Use the PR to discuss with current maintainer(s)
1. We prefer to see a history of contributing to the prometheus charts or other prometheus projects (not only typo PRs etc), to ensure the maintainers of charts have a good understanding of using and supporting these projects. This will make successful co-maintainership more likely, which will in turn help the end user community

Additional maintainer processes should be discussed in a separate issue, and documented in the [PROCESSES](https://github.com/prometheus-community/helm-charts/blob/main/PROCESSES.md) file

## Current status

Affected charts since issue was opened:
- [x] charts/prometheus-consul-exporter @timm088 @gkarthiks (#50)
- [ ] [prometheus-couchdb-exporter](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-couchdb-exporter) @gkarthiks
- [ ] [prometheus-mongodb-exporter](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-mongodb-exporter) @steven-sheehy
- [x] charts/prometheus-postgres-exporter @gianrubio @zanhsieh (#71)
- [ ] [prometheus-rabbitmq-exporter](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-rabbitmq-exporter) @Juanchimienti
- [x] charts/prometheus-redis-exporter @acondrat @zanhsieh (#46)
- [ ] [prometheus-snmp-exporter](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-snmp-exporter) @Miouge1
- [ ] [prometheus-to-sd](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-to-sd) @acondrat

## Original issue

> 📊  Maintainers poll
> Could any of your charts use additional maintainers?
>
> Let's use this issue to discuss. If it gets unwieldy, after we move to the `prometheus-community` GH org, we could consider enabling [team discussions](https://docs.github.com/en/github/building-a-strong-community/about-team-discussions) (but let's cross that bridge when we get there).

**Comment by gkarthiks** [comment]
Aah.. gotcha @scottrigby  I have a kafka-exporter chart as well. I will donate to the community group and continue to maintain here. Really awesome what you are doing here.

**Comment by scottrigby** [comment]
@gkarthiks sounds great!

**Comment by monotek** [comment]
I could Co maintain the prometheus chart. Did a bunch of pull requests there already.

**Comment by Xtigyro** [comment]
@monotek Message me  please on Kubernetes Community Slack workspace - Miro Hadzhiev.

**Comment by Xtigyro** [comment]
@scottrigby @brancz @vsliouniaev @bismarck @gianrubio
On my side - I'm willing to help as a maintainer the `kube-prometheus-stack` chart.

**Comment by scottrigby** [comment]
@Xtigyro IMO that would be helpful since @gianrubio has stepped back largely, and if I understood correctly @vsliouniaev and @bismarck work together, so sharing the load would probably be nice.

However, the current maintainers of each chart should decide on new maintainers for that chart (as long as they're responsive – i.e., the chart hasn't been abandoned. In this case they have been active recently, so we should wait for them to reply) 🙂

**Comment by monotek** [comment]
If somebody else is needed for blackbox-exporter chart i've could jump in too.

**Comment by torstenwalter** [comment]
When introducing CODEOWNERS we will have an issue with charts which only have one maintainers. If that maintainer make a change then he is not able to approve it. Repository admins would need to use their "superpower" to override the required review and can merge it. That might be ok for the start, but I would suggest that we try to add at least a second maintainer there.

Affected charts are:

- [ ] charts/prometheus-consul-exporter @timm088
- [ ] charts/prometheus-couchdb-exporter @gkarthiks
- [ ] charts/prometheus-mongodb-exporter @steven-sheehy
- [ ] charts/prometheus-postgres-exporter @gianrubio
- [ ] charts/prometheus-rabbitmq-exporter @Juanchimienti
- [ ] charts/prometheus-redis-exporter @acondrat
- [ ] charts/prometheus-snmp-exporter @Miouge1
- [ ] charts/prometheus-to-sd @acondrat

Would be great if we could fined volunteers here or even better if the chart maintainers could try to motivate people who already contributed to the chart to become maintainer.

**Comment by mrueg** [comment]
Happy to help out on the `kube-prometheus-stack` chart as well to share the load.

**Comment by zanhsieh** [comment]
I would like to help with:

- charts/prometheus-postgres-exporter
- charts/prometheus-redis-exporter

For charts/prometheus-postgres-exporter, I need you guys help to become one of OWNERs.

For charts/prometheus-redis-exporter, I will PR to see what @acondrat say.

**Comment by gkarthiks** [comment]
Adding myself as an additional maintainer for `charts/prometheus-consul-exporter`

/cc @timm088 @scottrigby

**Comment by torstenwalter** [comment]
I am updating the table above so that we keep track of which charts only have one maintainer.
Moving them to solved should not prevent anyone from adding additional maintainers if you want. It just means that we now have at least two maintainers and one could approve PRs or others.

As most of us doing this in there spare time and there are vacations and other times where one can not be as active it can't harm to hove more than two maintainers.

**Comment by monotek** [comment]
anyone likes to co maintain the prometheus-mysql-exporter chart?

or at least would approve my pr :D
https://github.com/prometheus-community/helm-charts/pull/68

**Comment by iamabhishek-dubey** [comment]
@scottrigby , I worked on druid exporter and donated the helm chart to the community as well. PR is already in the review process and I would like to maintain some other charts as well.

**Comment by fktkrt** [comment]
I'd also like to volunteer to maintain the `kube-prometheus-stack` chart.

**Comment by torstenwalter** [comment]
> @scottrigby , I worked on druid exporter and donated the helm chart to the community as well. PR is already in the review process and I would like to maintain some other charts as well.

@iamabhishek-dubey The list above shows which charts need more maintainers. If you are interested in one of those juts reach out to their maintainers and create a PR to add youself.

**Comment by scottrigby** [comment]
📣 update: I edited the description with clear steps to follow. We'll keep the summary and current status of this issue up to date there. Thanks!

**Comment by iamabhishek-dubey** [comment]
Adding myself as an additional maintainer for charts/prometheus-rabbitmq-exporter

**Comment by torstenwalter** [comment]
> Adding myself as an additional maintainer for charts/prometheus-rabbitmq-exporter

@iamabhishek-dubey did you already create a PR for that?

**Comment by iamabhishek-dubey** [comment]
> > Adding myself as an additional maintainer for charts/prometheus-rabbitmq-exporter
> 
> @iamabhishek-dubey did you already create a PR for that?

Yes here is the link https://github.com/prometheus-community/helm-charts/pull/282

**Comment by GMartinez-Sisti** [comment]
I just realized I'm not getting emails for PRs and such.

Some of the new maintainers need write access to the repository. The [CODEOWNERS](https://github.com/prometheus-community/helm-charts/blob/main/.github/CODEOWNERS) file reflects the ones with missing permissions.
